interface MemberDef {
    signature: MemberSignature
}

type MethodDef implements MemberDef {
    signature: MethodSignature
    argumentParams: [ParameterExpression]
    body: Expression!
    implements: [MethodReference]
}

type FieldDef implements MemberDef {
    signature: FieldSignature
}

type PropertyDef implements MemberDef {
    signature: PropertySignature
    getter: MethodDef!
    setter: MethodDef!
    implements: [PropertyReference]
}

type TypeDef implements MemberDef {
    signature: TypeSignature
    extends: SpecializedType!
    implements: [SpecializedType]
    members: [MemberDef]
}

type ModuleDef {
    topLevelTypes: [TypeDef]
}
