interface MemberDef {
    signature: MemberSignature
    doccomment: XmlComment!
}

type MethodDef implements MemberDef {
    signature: MethodSignature
    argumentParams: [ParameterExpression]
    body: Expression!
    implements: [MethodReference]
    doccomment: XmlComment! @default(value: null)
}

type FieldDef implements MemberDef {
    signature: FieldSignature
    doccomment: XmlComment! @default(value: null)
}

type PropertyDef implements MemberDef {
    signature: PropertySignature
    getter: MethodDef!
    setter: MethodDef!
    implements: [PropertyReference]
    doccomment: XmlComment! @default(value: null)
}

type TypeDef implements MemberDef {
    signature: TypeSignature
    extends: SpecializedType!
    implements: [SpecializedType]
    members: [MemberDef]
    doccomment: XmlComment! @default(value: null)
}

type ModuleDef {
    topLevelTypes: [TypeDef]
}

scalar XmlComment @validateXml(forFields: ["value"])
